---
- name: clear ios device
  hosts: ctaas
  gather_facts: no
  become: yes
  tasks:
    - name: erase config
      cli_command:
        command: wr er
        prompt:
          - Continue?
          - confirm
        answer:
          - confirm
